export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const CREATE_STORY_REQUEST = "CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAILURE = "CREATE_STORY_FAILURE";

export const GET_ALL_STORIES_REQUEST = "GET_ALL_STORIES_REQUEST";
export const GET_ALL_STORIES_SUCCESS = "GET_ALL_STORIES_SUCCESS";
export const GET_ALL_STORIES_FAILURE = "GET_ALL_STORIES_FAILURE";
